AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'spec/fixtures/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
  SuggestExtensions: false
Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table
Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
    - module_inclusion
    - constants
    - public_class_methods
    - initializer
    - instance_methods
    - protected_methods
    - private_methods
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/TrailingWhitespace:
  AllowInHeredoc: true
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Guardfile
Metrics/ClassLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search
StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - './*_helper.rb'
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - spec/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IpAddresses:
  # The test for this cop includes strings that would cause offenses
  Exclude:
    - spec/rubocop/cop/style/ip_addresses_spec.rb
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'
Style/StringLiterals:
  Exclude:
    - 'bin/yarn'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'test/application_system_test_case.rb'
# Nuevos
Style/RedundantParentheses:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

# Nuevos 2.0

Layout/SpaceBeforeBrackets:
  Enabled: true
Lint/AmbiguousAssignment:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
Style/HashExcept:
  Enabled: true
